// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMessage.proto

package com.tt.message.proto;

public final class BaseMessageProto {
  private BaseMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Int_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_Int_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_LongMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_LongMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_StringMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_StringMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_FloatMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_FloatMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_IntArray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_IntArray_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_LongArray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_LongArray_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_StringArray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_StringArray_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_FloatArray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_FloatArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BaseMessage.proto\022\017google.protobuf\"\024\n\003" +
      "Int\022\r\n\005value\030\001 \001(\005\"\030\n\007LongMsg\022\r\n\005value\030\001" +
      " \001(\003\"\032\n\tStringMsg\022\r\n\005value\030\001 \001(\t\"\031\n\010Floa" +
      "tMsg\022\r\n\005value\030\001 \001(\002\"\031\n\010IntArray\022\r\n\005value" +
      "\030\001 \003(\005\"\032\n\tLongArray\022\r\n\005value\030\001 \003(\003\"\034\n\013St" +
      "ringArray\022\r\n\005value\030\001 \003(\t\"\033\n\nFloatArray\022\r" +
      "\n\005value\030\001 \003(\002*/\n\nResultCode\022\013\n\007SUCCESS\020\000" +
      "\022\024\n\020MOVE_UNREACHABLE\020\001B*\n\024com.tt.message" +
      ".protoB\020BaseMessageProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_protobuf_Int_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_Int_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_Int_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_LongMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_protobuf_LongMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_LongMsg_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_StringMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_protobuf_StringMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_StringMsg_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_FloatMsg_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_protobuf_FloatMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_FloatMsg_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_IntArray_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_protobuf_IntArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_IntArray_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_LongArray_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_protobuf_LongArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_LongArray_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_StringArray_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_protobuf_StringArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_StringArray_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_FloatArray_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_protobuf_FloatArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_FloatArray_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
