// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMessage.proto

package com.tt.message.proto;

public interface FloatMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.FloatMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float value = 1;</code>
   * @return The value.
   */
  float getValue();
}
