// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world.proto

package com.tt.message.proto;

/**
 * Protobuf enum {@code google.protobuf.GameObjType}
 */
public enum GameObjType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PLAYER = 0;</code>
   */
  PLAYER(0),
  /**
   * <code>NPC = 1;</code>
   */
  NPC(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PLAYER = 0;</code>
   */
  public static final int PLAYER_VALUE = 0;
  /**
   * <code>NPC = 1;</code>
   */
  public static final int NPC_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GameObjType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static GameObjType forNumber(int value) {
    switch (value) {
      case 0: return PLAYER;
      case 1: return NPC;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GameObjType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GameObjType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GameObjType>() {
          public GameObjType findValueByNumber(int number) {
            return GameObjType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.tt.message.proto.WorldMessageProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final GameObjType[] VALUES = values();

  public static GameObjType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private GameObjType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:google.protobuf.GameObjType)
}

