// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMessage.proto

package com.tt.message.proto;

public interface IntArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.IntArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 value = 1;</code>
   * @return A list containing the value.
   */
  java.util.List<java.lang.Integer> getValueList();
  /**
   * <code>repeated int32 value = 1;</code>
   * @return The count of value.
   */
  int getValueCount();
  /**
   * <code>repeated int32 value = 1;</code>
   * @param index The index of the element to return.
   * @return The value at the given index.
   */
  int getValue(int index);
}
