// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMessage.proto

package com.tt.message.proto;

public interface IntOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Int)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   * @return The value.
   */
  int getValue();
}
