// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMessage.proto

package com.tt.message.proto;

public interface LongMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.LongMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 value = 1;</code>
   * @return The value.
   */
  long getValue();
}
