// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMessage.proto

package com.tt.message.proto;

public interface LongArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.LongArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 value = 1;</code>
   * @return A list containing the value.
   */
  java.util.List<java.lang.Long> getValueList();
  /**
   * <code>repeated int64 value = 1;</code>
   * @return The count of value.
   */
  int getValueCount();
  /**
   * <code>repeated int64 value = 1;</code>
   * @param index The index of the element to return.
   * @return The value at the given index.
   */
  long getValue(int index);
}
