// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMessage.proto

package com.tt.message.proto;

/**
 * Protobuf enum {@code google.protobuf.ResultCode}
 */
public enum ResultCode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 成功
   * </pre>
   *
   * <code>SUCCESS = 0;</code>
   */
  SUCCESS(0),
  /**
   * <pre>
   * 不可达
   * </pre>
   *
   * <code>MOVE_UNREACHABLE = 1;</code>
   */
  MOVE_UNREACHABLE(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 成功
   * </pre>
   *
   * <code>SUCCESS = 0;</code>
   */
  public static final int SUCCESS_VALUE = 0;
  /**
   * <pre>
   * 不可达
   * </pre>
   *
   * <code>MOVE_UNREACHABLE = 1;</code>
   */
  public static final int MOVE_UNREACHABLE_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ResultCode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ResultCode forNumber(int value) {
    switch (value) {
      case 0: return SUCCESS;
      case 1: return MOVE_UNREACHABLE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ResultCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
          public ResultCode findValueByNumber(int number) {
            return ResultCode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.tt.message.proto.BaseMessageProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final ResultCode[] VALUES = values();

  public static ResultCode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ResultCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:google.protobuf.ResultCode)
}

