// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world.proto

package com.tt.message.proto;

public interface SomeObjQuitViewOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.SomeObjQuitView)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 ids = 1;</code>
   * @return A list containing the ids.
   */
  java.util.List<java.lang.Long> getIdsList();
  /**
   * <code>repeated int64 ids = 1;</code>
   * @return The count of ids.
   */
  int getIdsCount();
  /**
   * <code>repeated int64 ids = 1;</code>
   * @param index The index of the element to return.
   * @return The ids at the given index.
   */
  long getIds(int index);
}
