// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world.proto

package com.tt.message.proto;

public interface SomeObjEnterViewMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.SomeObjEnterViewMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .google.protobuf.GameObjInfo objs = 1;</code>
   */
  java.util.List<com.tt.message.proto.GameObjInfo> 
      getObjsList();
  /**
   * <code>repeated .google.protobuf.GameObjInfo objs = 1;</code>
   */
  com.tt.message.proto.GameObjInfo getObjs(int index);
  /**
   * <code>repeated .google.protobuf.GameObjInfo objs = 1;</code>
   */
  int getObjsCount();
  /**
   * <code>repeated .google.protobuf.GameObjInfo objs = 1;</code>
   */
  java.util.List<? extends com.tt.message.proto.GameObjInfoOrBuilder> 
      getObjsOrBuilderList();
  /**
   * <code>repeated .google.protobuf.GameObjInfo objs = 1;</code>
   */
  com.tt.message.proto.GameObjInfoOrBuilder getObjsOrBuilder(
      int index);
}
