// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.tt.message.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\017google.protobuf\032\013world.pro" +
      "to\"_\n\004User\022\013\n\003uid\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022,\n" +
      "\006vector\030\003 \001(\0132\034.google.protobuf.VectorPr" +
      "oto\022\016\n\006toward\030\004 \001(\002B#\n\024com.tt.message.pr" +
      "otoB\tUserProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tt.message.proto.WorldMessageProto.getDescriptor(),
        });
    internal_static_google_protobuf_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_User_descriptor,
        new java.lang.String[] { "Uid", "Name", "Vector", "Toward", });
    com.tt.message.proto.WorldMessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
