// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.tt.message.proto;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 uid = 1;</code>
   * @return The uid.
   */
  long getUid();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 位置信息
   * </pre>
   *
   * <code>.google.protobuf.VectorProto vector = 3;</code>
   * @return Whether the vector field is set.
   */
  boolean hasVector();
  /**
   * <pre>
   * 位置信息
   * </pre>
   *
   * <code>.google.protobuf.VectorProto vector = 3;</code>
   * @return The vector.
   */
  com.tt.message.proto.VectorProto getVector();
  /**
   * <pre>
   * 位置信息
   * </pre>
   *
   * <code>.google.protobuf.VectorProto vector = 3;</code>
   */
  com.tt.message.proto.VectorProtoOrBuilder getVectorOrBuilder();

  /**
   * <code>float toward = 4;</code>
   * @return The toward.
   */
  float getToward();
}
