// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.tt.message.proto;

/**
 * Protobuf type {@code google.protobuf.User}
 */
public final class User extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.protobuf.User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new User();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private User(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            uid_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            com.tt.message.proto.VectorProto.Builder subBuilder = null;
            if (vector_ != null) {
              subBuilder = vector_.toBuilder();
            }
            vector_ = input.readMessage(com.tt.message.proto.VectorProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(vector_);
              vector_ = subBuilder.buildPartial();
            }

            break;
          }
          case 37: {

            toward_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tt.message.proto.UserProto.internal_static_google_protobuf_User_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tt.message.proto.UserProto.internal_static_google_protobuf_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tt.message.proto.User.class, com.tt.message.proto.User.Builder.class);
  }

  public static final int UID_FIELD_NUMBER = 1;
  private long uid_;
  /**
   * <code>int64 uid = 1;</code>
   * @return The uid.
   */
  @java.lang.Override
  public long getUid() {
    return uid_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VECTOR_FIELD_NUMBER = 3;
  private com.tt.message.proto.VectorProto vector_;
  /**
   * <pre>
   * 位置信息
   * </pre>
   *
   * <code>.google.protobuf.VectorProto vector = 3;</code>
   * @return Whether the vector field is set.
   */
  @java.lang.Override
  public boolean hasVector() {
    return vector_ != null;
  }
  /**
   * <pre>
   * 位置信息
   * </pre>
   *
   * <code>.google.protobuf.VectorProto vector = 3;</code>
   * @return The vector.
   */
  @java.lang.Override
  public com.tt.message.proto.VectorProto getVector() {
    return vector_ == null ? com.tt.message.proto.VectorProto.getDefaultInstance() : vector_;
  }
  /**
   * <pre>
   * 位置信息
   * </pre>
   *
   * <code>.google.protobuf.VectorProto vector = 3;</code>
   */
  @java.lang.Override
  public com.tt.message.proto.VectorProtoOrBuilder getVectorOrBuilder() {
    return getVector();
  }

  public static final int TOWARD_FIELD_NUMBER = 4;
  private float toward_;
  /**
   * <code>float toward = 4;</code>
   * @return The toward.
   */
  @java.lang.Override
  public float getToward() {
    return toward_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uid_ != 0L) {
      output.writeInt64(1, uid_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (vector_ != null) {
      output.writeMessage(3, getVector());
    }
    if (toward_ != 0F) {
      output.writeFloat(4, toward_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, uid_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (vector_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getVector());
    }
    if (toward_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, toward_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tt.message.proto.User)) {
      return super.equals(obj);
    }
    com.tt.message.proto.User other = (com.tt.message.proto.User) obj;

    if (getUid()
        != other.getUid()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (hasVector() != other.hasVector()) return false;
    if (hasVector()) {
      if (!getVector()
          .equals(other.getVector())) return false;
    }
    if (java.lang.Float.floatToIntBits(getToward())
        != java.lang.Float.floatToIntBits(
            other.getToward())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUid());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasVector()) {
      hash = (37 * hash) + VECTOR_FIELD_NUMBER;
      hash = (53 * hash) + getVector().hashCode();
    }
    hash = (37 * hash) + TOWARD_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getToward());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tt.message.proto.User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tt.message.proto.User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tt.message.proto.User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tt.message.proto.User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tt.message.proto.User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tt.message.proto.User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tt.message.proto.User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tt.message.proto.User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tt.message.proto.User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tt.message.proto.User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tt.message.proto.User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tt.message.proto.User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tt.message.proto.User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.protobuf.User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.User)
      com.tt.message.proto.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tt.message.proto.UserProto.internal_static_google_protobuf_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tt.message.proto.UserProto.internal_static_google_protobuf_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tt.message.proto.User.class, com.tt.message.proto.User.Builder.class);
    }

    // Construct using com.tt.message.proto.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uid_ = 0L;

      name_ = "";

      if (vectorBuilder_ == null) {
        vector_ = null;
      } else {
        vector_ = null;
        vectorBuilder_ = null;
      }
      toward_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tt.message.proto.UserProto.internal_static_google_protobuf_User_descriptor;
    }

    @java.lang.Override
    public com.tt.message.proto.User getDefaultInstanceForType() {
      return com.tt.message.proto.User.getDefaultInstance();
    }

    @java.lang.Override
    public com.tt.message.proto.User build() {
      com.tt.message.proto.User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tt.message.proto.User buildPartial() {
      com.tt.message.proto.User result = new com.tt.message.proto.User(this);
      result.uid_ = uid_;
      result.name_ = name_;
      if (vectorBuilder_ == null) {
        result.vector_ = vector_;
      } else {
        result.vector_ = vectorBuilder_.build();
      }
      result.toward_ = toward_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tt.message.proto.User) {
        return mergeFrom((com.tt.message.proto.User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tt.message.proto.User other) {
      if (other == com.tt.message.proto.User.getDefaultInstance()) return this;
      if (other.getUid() != 0L) {
        setUid(other.getUid());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasVector()) {
        mergeVector(other.getVector());
      }
      if (other.getToward() != 0F) {
        setToward(other.getToward());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tt.message.proto.User parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tt.message.proto.User) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long uid_ ;
    /**
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public long getUid() {
      return uid_;
    }
    /**
     * <code>int64 uid = 1;</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(long value) {
      
      uid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 uid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      
      uid_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private com.tt.message.proto.VectorProto vector_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tt.message.proto.VectorProto, com.tt.message.proto.VectorProto.Builder, com.tt.message.proto.VectorProtoOrBuilder> vectorBuilder_;
    /**
     * <pre>
     * 位置信息
     * </pre>
     *
     * <code>.google.protobuf.VectorProto vector = 3;</code>
     * @return Whether the vector field is set.
     */
    public boolean hasVector() {
      return vectorBuilder_ != null || vector_ != null;
    }
    /**
     * <pre>
     * 位置信息
     * </pre>
     *
     * <code>.google.protobuf.VectorProto vector = 3;</code>
     * @return The vector.
     */
    public com.tt.message.proto.VectorProto getVector() {
      if (vectorBuilder_ == null) {
        return vector_ == null ? com.tt.message.proto.VectorProto.getDefaultInstance() : vector_;
      } else {
        return vectorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 位置信息
     * </pre>
     *
     * <code>.google.protobuf.VectorProto vector = 3;</code>
     */
    public Builder setVector(com.tt.message.proto.VectorProto value) {
      if (vectorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        vector_ = value;
        onChanged();
      } else {
        vectorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 位置信息
     * </pre>
     *
     * <code>.google.protobuf.VectorProto vector = 3;</code>
     */
    public Builder setVector(
        com.tt.message.proto.VectorProto.Builder builderForValue) {
      if (vectorBuilder_ == null) {
        vector_ = builderForValue.build();
        onChanged();
      } else {
        vectorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 位置信息
     * </pre>
     *
     * <code>.google.protobuf.VectorProto vector = 3;</code>
     */
    public Builder mergeVector(com.tt.message.proto.VectorProto value) {
      if (vectorBuilder_ == null) {
        if (vector_ != null) {
          vector_ =
            com.tt.message.proto.VectorProto.newBuilder(vector_).mergeFrom(value).buildPartial();
        } else {
          vector_ = value;
        }
        onChanged();
      } else {
        vectorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 位置信息
     * </pre>
     *
     * <code>.google.protobuf.VectorProto vector = 3;</code>
     */
    public Builder clearVector() {
      if (vectorBuilder_ == null) {
        vector_ = null;
        onChanged();
      } else {
        vector_ = null;
        vectorBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 位置信息
     * </pre>
     *
     * <code>.google.protobuf.VectorProto vector = 3;</code>
     */
    public com.tt.message.proto.VectorProto.Builder getVectorBuilder() {
      
      onChanged();
      return getVectorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 位置信息
     * </pre>
     *
     * <code>.google.protobuf.VectorProto vector = 3;</code>
     */
    public com.tt.message.proto.VectorProtoOrBuilder getVectorOrBuilder() {
      if (vectorBuilder_ != null) {
        return vectorBuilder_.getMessageOrBuilder();
      } else {
        return vector_ == null ?
            com.tt.message.proto.VectorProto.getDefaultInstance() : vector_;
      }
    }
    /**
     * <pre>
     * 位置信息
     * </pre>
     *
     * <code>.google.protobuf.VectorProto vector = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tt.message.proto.VectorProto, com.tt.message.proto.VectorProto.Builder, com.tt.message.proto.VectorProtoOrBuilder> 
        getVectorFieldBuilder() {
      if (vectorBuilder_ == null) {
        vectorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tt.message.proto.VectorProto, com.tt.message.proto.VectorProto.Builder, com.tt.message.proto.VectorProtoOrBuilder>(
                getVector(),
                getParentForChildren(),
                isClean());
        vector_ = null;
      }
      return vectorBuilder_;
    }

    private float toward_ ;
    /**
     * <code>float toward = 4;</code>
     * @return The toward.
     */
    @java.lang.Override
    public float getToward() {
      return toward_;
    }
    /**
     * <code>float toward = 4;</code>
     * @param value The toward to set.
     * @return This builder for chaining.
     */
    public Builder setToward(float value) {
      
      toward_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float toward = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearToward() {
      
      toward_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.protobuf.User)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.User)
  private static final com.tt.message.proto.User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tt.message.proto.User();
  }

  public static com.tt.message.proto.User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    @java.lang.Override
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new User(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tt.message.proto.User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

