// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world.proto

package com.tt.message.proto;

public interface VectorProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.VectorProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float x = 1;</code>
   * @return The x.
   */
  float getX();

  /**
   * <code>float y = 2;</code>
   * @return The y.
   */
  float getY();

  /**
   * <code>float z = 3;</code>
   * @return The z.
   */
  float getZ();
}
