// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world.proto

package com.tt.message.proto;

public final class WorldMessageProto {
  private WorldMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_VectorProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_VectorProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_GameObjInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_GameObjInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_ChangePosition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_ChangePosition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_PlayerObjInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_PlayerObjInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_SomeObjEnterViewMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_SomeObjEnterViewMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_SomeObjQuitView_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_SomeObjQuitView_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013world.proto\022\017google.protobuf\032\031google/p" +
      "rotobuf/any.proto\".\n\013VectorProto\022\t\n\001x\030\001 " +
      "\001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\"\315\001\n\013GameObjInf" +
      "o\022\n\n\002id\030\001 \001(\003\022.\n\010position\030\002 \001(\0132\034.google" +
      ".protobuf.VectorProto\022\016\n\006toward\030\003 \001(\002\022*\n" +
      "\004type\030\004 \001(\0162\034.google.protobuf.GameObjTyp" +
      "e\022,\n\016typeExtendInfo\030\005 \001(\0132\024.google.proto" +
      "buf.Any\022\030\n\020moveToOtherTower\030\006 \001(\010\"\\\n\016Cha" +
      "ngePosition\022\n\n\002id\030\001 \001(\003\022.\n\010position\030\002 \001(" +
      "\0132\034.google.protobuf.VectorProto\022\016\n\006towar" +
      "d\030\003 \001(\002\"*\n\rPlayerObjInfo\022\013\n\003uid\030\001 \001(\003\022\014\n" +
      "\004name\030\002 \001(\t\"E\n\027SomeObjEnterViewMessage\022*" +
      "\n\004objs\030\001 \003(\0132\034.google.protobuf.GameObjIn" +
      "fo\"\036\n\017SomeObjQuitView\022\013\n\003ids\030\001 \003(\003*\"\n\013Ga" +
      "meObjType\022\n\n\006PLAYER\020\000\022\007\n\003NPC\020\001B+\n\024com.tt" +
      ".message.protoB\021WorldMessageProtoP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_google_protobuf_VectorProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_VectorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_VectorProto_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_google_protobuf_GameObjInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_protobuf_GameObjInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_GameObjInfo_descriptor,
        new java.lang.String[] { "Id", "Position", "Toward", "Type", "TypeExtendInfo", "MoveToOtherTower", });
    internal_static_google_protobuf_ChangePosition_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_protobuf_ChangePosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_ChangePosition_descriptor,
        new java.lang.String[] { "Id", "Position", "Toward", });
    internal_static_google_protobuf_PlayerObjInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_protobuf_PlayerObjInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_PlayerObjInfo_descriptor,
        new java.lang.String[] { "Uid", "Name", });
    internal_static_google_protobuf_SomeObjEnterViewMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_protobuf_SomeObjEnterViewMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_SomeObjEnterViewMessage_descriptor,
        new java.lang.String[] { "Objs", });
    internal_static_google_protobuf_SomeObjQuitView_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_protobuf_SomeObjQuitView_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_SomeObjQuitView_descriptor,
        new java.lang.String[] { "Ids", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
